name: convention_list
description: "App to locate conventions"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  infinite_scroll_pagination: ^4.0.0
  build_runner: ^2.4.13
  intl: ^0.19.0
  expandable_text: ^2.3.0
  flutter_spinkit: ^5.2.1
  auth0_flutter: ^1.1.0
  url_launcher: ^6.3.1
  rxdart: ^0.28.0
  geolocator: ^13.0.1
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  go_router: ^14.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  freezed_annotation: ^2.4.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.1
  jwt_decoder: ^2.0.1
  form_builder_extra_fields: ^11.0.0
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  firebase_core: ^3.8.0
  get_it: ^8.0.2
  injectable: ^2.5.0
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
