name: Deploy ASP.NET Core API to DigitalOcean

on:
  push:
    branches:
      - main
    paths:
      - src/api/**

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: List files
        run: ls -lA src/api

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/api

      - name: Update appsettings.Production.json
        run: |
          jq '.ConnectionStrings.PostgresDatabaseConventionList = "${{ secrets.POSTGRES_CONNECTION_STRING }}" | .GoogleMaps.ApiKey = "${{ secrets.GOOGLE_MAPS_API_KEY }}"' ./src/api/ConventionList.Api/appsettings.Production.json > ./src/api/ConventionList.Api/appsettings.Production.tmp.json
          mv ./src/api/ConventionList.Api/appsettings.Production.tmp.json ./src/api/ConventionList.Api/appsettings.Production.json

      - name: Build the project
        run: dotnet publish -c Release -o out
        working-directory: ./src/api

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          source: "./src/api/out/*"
          target: "/var/www/conventionlist" # Change this to your desired location on the Droplet
          strip_components: 3

      - name: Restart application via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            # Stop existing application process if running
            if pgrep dotnet; then pkill dotnet; fi
            # Start the application
            cd /var/www/conventionlist
            nohup dotnet ConventionList.Api.dll > /dev/null 2>&1 &
