name: Deploy ASP.NET Core API to DigitalOcean

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # Specify the .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Update appsettings.Production.json
        run: |
          jq '.ConnectionStrings.PostgresDatabaseConventionList = "${{ secrets.POSTGRES_CONNECTION_STRING }}" | .GoogleMaps.ApiKey = "${{ secrets.GOOGLE_MAPS_API_KEY }}"' appsettings.Production.json > appsettings.Production.tmp.json
          mv appsettings.Production.tmp.json appsettings.Production.json

      - name: Build the project
        run: dotnet publish -c Release -o out

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          source: "out/"
          target: "/var/www/conventionlist" # Change this to your desired location on the Droplet

      - name: Restart application via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            # Stop existing application process if running
            if pgrep dotnet; then pkill dotnet; fi
            # Start the application
            nohup dotnet /var/www/myapp/ConventionList.Api.dll > /dev/null 2>&1 &
