name: Deploy to Netlify

on:
  push:
    branches:
      - main
    paths:
      - src/webclient/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install
        working-directory: src/api/webclient

      - name: Build the site
        run: npm run build
        working-directory: src/api/webclient

      - name: Deploy to Netlify
        working-directory: src/api/webclient
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=./dist --prod --site=$NETLIFY_SITE_ID
